# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Folder Rsync"
  org.opencontainers.image.description: "Transfers the Hass.io folders to a remote rsync server."
  org.opencontainers.image.source: "https://github.com/Meetsch/hassio-addons"
  org.opencontainers.image.licenses: "MIT License"
#args:
#  TEMPIO_VERSION: "2021.09.0"