name: "Crowdsec"
description: "CrowdSec - the open-source and participative IPS"
url: "https://github.com/thywolf/hassio-addons/blob/main/crowdsec/DOCS.md"
version: "1.3.4-ha2"
slug: "crowdsec"
init: false
ingress: true
ingress_port: 7681
ingress_stream: true
arch:
  - amd64
  - armhf
  - aarch64
  - armv7
  - i386
image: "ghcr.io/crowdsecurity/{arch}-addon-crowdsec"
options:
  acquisition: |
    ---
    source: journalctl
    journalctl_filter: 
      - "--directory=/var/log/journal/"
    labels:
      type: syslog
  collections:
    - crowdsecurity/home-assistant
  parsers: []
  scenarios: []
  postoverflows: []
  parsers_to_disable: []
  scenarios_to_disable: []
  disable_online_api: false
environment:
  CONFIG_FILE: "/config/.storage/crowdsec/config/config.yaml"
  DISABLE_LOCAL_API: "true"
  AGENT_USERNAME: "HomeAssistant"
  AGENT_PASSWORD: "fYR43QAiqQ3BSU0rbe2nvHoKjXp01H8SRR0FXHLQgqgjiOvqXleLURY1S1Kwz6Bc"
  LOCAL_API_URL: "http://192.168.0.4:8080"
schema:
  acquisition: str
  collections:
    - str
  parsers:
    - str
  scenarios:
    - str
  postoverflows:
    - str
  parsers_to_disable:
    - str
  scenarios_to_disable:
    - str
  disable_online_api: bool
  disable_local_api: bool
  agent_username: str
  agent_password: password
  local_api_url: str
map:
  - config:rw
panel_icon: mdi:console-network
panel_title: Crowdsec Terminal
journald: true